---
- name: Copy deployment script file to remote machine
  copy:
    src: alert-deploy-java-manager.sh
    dest: /var/tmp/alert-deploy-java-manager.sh
    mode: 0777

- name: Execute shell script
  shell: sh /var/tmp/alert-deploy-java-manager.sh {{VERSION}} {{PLATFORM}} {{MANAGER}} > /var/tmp/alert-deploy-java-manager.log
  args:
    chdir: /var/tmp/
