---
- name: Copy deployment script file to remote machine
  copy:
    src: alert-deploy-java-manager.sh
    dest: alert-deploy-java-manager.sh
    mode: 0777

- name: Execute shell script
  shell: sh alert-deploy-java-manager.sh  > /var/tmp/alert-deploy-java-manager.log
  
- name: Display vault passwd
  shell: echo 'Vault passwd is "{{ TEST_PASSWORD }}"'
  register: results
  
- debug:
    var: result
    verbosity: 2
